defaults:
  - _self_
  - model: xgboost
  - override hydra/sweeper: basic

raw_data:
  path: "data/raw/heart.csv"

processed_data:
  dir: "data/processed"
  train_path: "data/processed/train.csv"
  test_path: "data/processed/test.csv"


processing:
  missing_vals_cols: ["Cholesterol", "RestingBP"]  # 0 -> NaN
  cat_features: ["Sex", "ChestPainType", "RestingECG", "ExerciseAngina", "ST_Slope"]
  num_features: ["Age", "RestingBP", "Cholesterol", "FastingBS", "MaxHR", "Oldpeak"]
  cat_impute_strategy: "most_frequent"
  num_impute_strategy: "median"

#hydra:
#  sweeper:
#    sampler:
#      seed: 123
#    direction: maximize
#    study_name: xgboost_optimization
#    storage: null
#    n_trials: 20
#    n_jobs: 1
#
#    params:
#      # model.estimator.n_estimators: choice(75, 100, 150)
#      model.estimator.max_depth: range(3, 6)
#      model.estimator.learning_rate: interval(0.05, 0.15)
#      model.estimator.scale_pos_weight: range(5, 11)
